import Bun from 'bun';
import Baker from "cronbake";
import { SQL } from 'bun';

let RequestsCount = 0;
const sql = new SQL(Bun.env.DB_URL!, {
    // Limit connections to 1
    max: 1
});

await sql.connect();
await sql`CREATE SCHEMA IF NOT EXISTS APP`;

// Create the table
await sql`CREATE TABLE IF NOT EXISTS APP.REQUESTS_COUNT (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TS TIMESTAMP DEFAULT NOW(),
    SERVER INT,
    COUNT INT
)`;

// Select last requests count
RequestsCount = (await sql`
SELECT COUNT
FROM APP.REQUESTS_COUNT
ORDER BY ID DESC
LIMIT 1
`)[0]?.count || 0;

console.log('Loaded last request count:', RequestsCount);

Bun.serve({
    fetch: () => {
        RequestsCount++;
        return new Response(`Request ID: ${Bun.randomUUIDv7()}, Count: ${RequestsCount}`);
    },
    port: 3000
});

// Setup cron jobs
const cronjobs = new Baker();

// Update the request count every 2 minutes
cronjobs.add({
    name: 'Store Requests To DB',
    cron: '@every_2_minutes',
    // Do not store the value immediately
    immediate: false,
    callback: async () => {
        console.log('Storing requests count into DB:', RequestsCount);

        await sql`
            INSERT INTO APP.REQUESTS_COUNT (count, server) VALUES (${RequestsCount}, ${Bun.env.SERVER_ID})
        `;
    },
});

// Start all jobs
cronjobs.bakeAll();