import Bun from 'bun';
import Baker from "cronbake";
import { SQL } from 'bun';

let RequestsCount = 0;
const sql = new SQL(Bun.env.DB_URL!, {
    // Limit connections to 1
    max: 1
});

await sql.connect();
await sql`CREATE SCHEMA IF NOT EXISTS APP`;

// Create the table
await sql`CREATE TABLE IF NOT EXISTS APP.REQUESTS_COUNT (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TS TIMESTAMP DEFAULT NOW(),
    SERVER INT,
    INSTANCE INT,
    COUNT INT
)`;

// Select last requests count
RequestsCount = (await sql`
SELECT COUNT
FROM APP.REQUESTS_COUNT
ORDER BY ID DESC
LIMIT 1
`)[0]?.count || 0;

console.log('Loaded last request count:', RequestsCount);

Bun.serve({
    fetch: () => {
        RequestsCount++;
        return new Response(`Request ID: ${Bun.randomUUIDv7()}, Count: ${RequestsCount}`);
    },
    port: 3000,
    reusePort: true
});

// Setup cron jobs
const cronjobs = new Baker();

// Update the request count every 2 minutes
cronjobs.add({
    name: 'Store Requests To DB',
    cron: '@every_5_minutes',
    // Do not store the value immediately
    // immediate: false,
    immediate: true,
    callback: async () => {
        console.log('Storing requests count into DB:', RequestsCount);
        // Server id format: [server id][instance id]
        // Example: 11 Will be server 1 instance 1. 12 Will be server 1 instance 2.
        await sql`
            INSERT INTO APP.REQUESTS_COUNT (count, server, instance) VALUES (${RequestsCount}, ${Bun.env.SERVER_ID}, ${Bun.env.NODE_APP_INSTANCE})
        `;
    },
});

// Start all jobs
cronjobs.bakeAll();

console.log(`[-] Server ${Bun.env.SERVER_ID} Instance ${Bun.env.NODE_APP_INSTANCE} Created!`);